# Generated by Django 5.0.7 on 2024-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('absent_value', models.IntegerField()),
                ('late_value', models.IntegerField()),
                ('referral_value', models.IntegerField()),
                ('visitors_value', models.IntegerField()),
                ('TYFCB_value', models.IntegerField()),
                ('training_value', models.IntegerField()),
                ('testimonial_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberTrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('training_attended', models.IntegerField()),
            ],
        ),
    ]
